name: Feature request
description: Suggest features, propose improvements, discuss new ideas
title: "[FEATURE]: "
labels: ["🚀 feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the change or addition you are proposing.
    validations:
      required: true
  - type: textarea
    id: possible_sol
    attributes:
      label: Possible solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: List any possible alternatives to your current request.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional information
      description: Is there anything else we should know about this feature request?
    validations:
      required: false
