name: Vitest Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    - name: Install dependencies
      run: yarn
    - name: Run Vitest tests
      run: yarn test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: vitest-report
        path: vitest-report/
        retention-days: 30
